#!/usr/bin/python
from scapy.all import *

file = open("torDataFile.txt","w+")

def packetSpoof(pkt):
	
	IPInfo=IP()
	TCPinfo=TCP()
	Data=pkt[TCP].data
	packet = [IPinfo, TCPinfo, Data]
	file.writelines(packet)	

pkt=sniff(prn=packetSpoof)

file.close()w")
ListLength = len(PacketList)
for i in range(ListLength):
	file.write(PacketList[i])

file.close()
